/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xml;

import java.awt.event.ItemEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static xml.WriteXMLFile.txtToXml;

/**
 *
 * @author ruben
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() throws ClassNotFoundException, SQLException {
        initComponents();
        buttonGroup1.add(radioTodo);
        buttonGroup1.add(radioProvincia);
        buttonGroup1.add(radioCanton);
        comboBoxProvincia.removeAllItems();
        comboBoxProvincia.addItem("San Jose");
        comboBoxProvincia.addItem("Alajuela");
        comboBoxProvincia.addItem("Cartago");
        comboBoxProvincia.addItem("Heredia");
        comboBoxProvincia.addItem("Guanacaste");
        comboBoxProvincia.addItem("Puntarenas");
        comboBoxProvincia.addItem("Limon");
        comboBoxProvincia.addItem("Extranjero");
        comboBoxProvincia.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                Object item = e.getItem();
                switch (item.toString()) {
                    case "San Jose":
                        System.out.println("San Jose");
                }
            }
        });
        sql();
        
    }

    public void sql() throws ClassNotFoundException, SQLException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

        Connection con = DriverManager.getConnection("jdbc:sqlserver:SQLMASTER\\SQLAMSTER;databaseName=Elecciones", "sa", "Bases2018");

        CallableStatement proc_stmt = con.prepareCall("{ call getCantones(?) }");

        proc_stmt.setString(1, "1");
        ResultSet rs = proc_stmt.executeQuery();

        if (rs.next()) {
            int employeeId = rs.getInt(1);
            System.out.println("Generated employeeId: " + employeeId);
        } else {
            System.out.println("Stored procedure couldn't generate new Id");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        comboBoxProvincia = new javax.swing.JComboBox<>();
        comboCanton = new javax.swing.JComboBox<>();
        radioTodo = new javax.swing.JRadioButton();
        radioProvincia = new javax.swing.JRadioButton();
        radioCanton = new javax.swing.JRadioButton();
        buttonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboCanton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        radioTodo.setText("Todo");

        radioProvincia.setText("Provincia");

        radioCanton.setText("Canton");

        buttonOk.setText("Añadir");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(radioTodo)
                            .addGap(18, 18, 18)
                            .addComponent(radioProvincia)
                            .addGap(18, 18, 18)
                            .addComponent(radioCanton))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(comboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(buttonOk)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTodo)
                    .addComponent(radioProvincia)
                    .addComponent(radioCanton))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(buttonOk)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        if (radioProvincia.isSelected()) {
            int IDProvincia = comboBoxProvincia.getSelectedIndex();
            switch (IDProvincia) {
                case 0:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\SJ.txt");
                    break;
                case 1:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\AL.txt");
                    break;
                case 2:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\CA.txt");
                    break;
                case 3:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\HE.txt");
                    break;
                case 4:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\GU.txt");
                    break;
                case 5:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\PU.txt");
                    break;
                case 6:
                    txtToXml("C:\\Users\\ruben\\Downloads\\Provincias\\LI.txt");
                    break;
            }
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new View().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox<String> comboBoxProvincia;
    private javax.swing.JComboBox<String> comboCanton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioCanton;
    private javax.swing.JRadioButton radioProvincia;
    private javax.swing.JRadioButton radioTodo;
    // End of variables declaration//GEN-END:variables
}
